[package]
name = "trackingbot"
version = "0.0.1"
authors = ["dstu <dstu93@noreply-github.com>"]

[dependencies]
postgres = "*"
mysql = "*"
teleborg = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive   = "1.0"

[dev-dependencies]
mock-it = "0.2.0"